name: auto_text_bouncer
description: A Flutter package for creating auto-scrolling text with bouncing effect.
version: 0.1.0
homepage: https://github.com/miraskoda/auto_text_bouncer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_scroll_text: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 